const {chromium}=require('C:/Users/ZHP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs'),cp=require('child_process'),assert=require('assert/strict');
(async()=>{const b=await chromium.connectOverCDP('http://127.0.0.1:9227'),c=b.contexts()[0],main=c.pages().find(p=>!p.url().includes('?window='));const errors=[];c.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));const invoke=(p,cmd,args={})=>p.evaluate(({cmd,args})=>__TAURI_INTERNALS__.invoke(cmd,args),{cmd,args});await main.getByRole('button',{name:'创建第一个项目'}).waitFor();const data=await invoke(main,'load');assert.ok(data.dataDir.includes('desktop-test-notebook'));const pid=fs.readFileSync('.tools/desktop-test.pid','utf8').trim(),oldCursor=await invoke(main,'plugin:window|cursor_position');const cursor=(x,y)=>cp.execFileSync('powershell.exe',['-NoProfile','-File','tests/move-test-window.ps1','-TestProcessId',pid,'-X',String(Math.round(x)),'-Y',String(Math.round(y)),'-CursorOnly'],{windowsHide:true});
const win=async kind=>{for(let i=0;i<200;i++){const p=c.pages().find(p=>p.url().includes('window='+kind));if(p){await p.waitForLoadState('domcontentloaded');return p;}await main.waitForTimeout(100);}throw Error('No '+kind)};
let cursorRestored=false;
try{
 await main.getByLabel('更多',{exact:true}).click();let more=await win('more');await more.getByLabel('笔记本模式',{exact:true}).check();await more.getByLabel('自动收起等待时间').selectOption('15');const size=await invoke(main,'plugin:window|outer_size',{label:'main'});
 cursor(2400,1250);await main.waitForTimeout(17000);assert.equal(await invoke(main,'plugin:window|is_visible',{label:'main'}),true,'settings pauses idle collapse');
 await invoke(more,'plugin:window|close',{label:'more'});let bubble=await win('bubble');await bubble.getByLabel('展开笔记本').waitFor();await bubble.waitForFunction(()=>__TAURI_INTERNALS__.invoke('plugin:window|is_visible',{label:'bubble'}));await bubble.waitForTimeout(300);await main.waitForFunction(()=>__TAURI_INTERNALS__.invoke('plugin:window|is_visible',{label:'main'}).then(v=>!v));assert.equal(await invoke(bubble,'bubble_status'),false);const compactSize=await invoke(bubble,'plugin:window|outer_size',{label:'bubble'});const compactScale=await invoke(bubble,'plugin:window|scale_factor',{label:'bubble'});assert.equal(compactSize.width,40*compactScale);assert.equal(compactSize.height,48*compactScale);await bubble.screenshot({path:'.tools/notebook-floating.png'});
 const initial=await invoke(bubble,'plugin:window|outer_position',{label:'bubble'});const drag=(x,y)=>cp.execFileSync('powershell.exe',['-NoProfile','-File','tests/drag-notebook.ps1','-TestProcessId',pid,'-FromX',String(Math.round(x.from)),'-FromY',String(Math.round(y.from)),'-ToX',String(Math.round(x.to)),'-ToY',String(Math.round(y.to))],{windowsHide:true});
 drag({from:initial.x+20,to:20},{from:initial.y+24,to:400});await bubble.waitForFunction(()=>__TAURI_INTERNALS__.invoke('bubble_status'));assert.equal(await invoke(bubble,'bubble_status'),true,'native drag docks compact notebook');assert.equal(await invoke(main,'plugin:window|is_visible',{label:'main'}),false,'drag must not open main');await bubble.screenshot({path:'.tools/notebook-dot.png'});
 const dotPos=await invoke(bubble,'plugin:window|outer_position',{label:'bubble'});drag({from:dotPos.x+12,to:700},{from:dotPos.y+12,to:500});await main.waitForTimeout(500);assert.equal(await invoke(bubble,'bubble_status'),false);assert.equal(await invoke(main,'plugin:window|is_visible',{label:'main'}),false);
 await bubble.getByLabel('展开笔记本').click();await main.waitForFunction(()=>__TAURI_INTERNALS__.invoke('plugin:window|is_visible',{label:'main'}));assert.deepEqual(await invoke(main,'plugin:window|outer_size',{label:'main'}),size);
 await main.getByLabel('更多',{exact:true}).click();more=await win('more');await more.getByLabel('笔记本模式',{exact:true}).uncheck();await invoke(more,'plugin:window|close',{label:'more'});assert.equal(await main.getByLabel('收起为悬浮笔记本').count(),1);
 const project=await invoke(main,'create_project',{name:'二十条交付验收'});for(let i=0;i<20;i++){await invoke(main,'save_entry',{entry:{id:'note-'+i,projectId:project.id,type:'Note',text:'独立记录 '+i,createdAt:new Date(1700000000000+i*1000).toISOString(),updatedAt:new Date().toISOString(),tags:[],status:'Open',attachments:[],references:[]}});}await main.reload();await main.locator('article').first().waitFor();await main.keyboard.press('Control+a');await main.getByRole('button',{name:'交给 Agent',exact:true}).click();const delivery=await win('delivery');const preview=delivery.getByLabel('Agent 提示词预览');assert.equal(await delivery.locator('.delivery-summary').innerText().then(t=>t.includes('20 条记录')),true);let text=await preview.inputValue();assert.ok(text.indexOf('独立记录 0')<text.indexOf('独立记录 19'));await delivery.getByLabel('交付顺序').selectOption('newest');text=await preview.inputValue();assert.ok(text.indexOf('独立记录 19')<text.indexOf('独立记录 0'));await delivery.screenshot({path:'.tools/notebook-delivery.png'});assert.deepEqual(errors,[]);fs.writeFileSync('.tools/notebook-result.json',JSON.stringify({passed:true,auxPauses:true,idleCollapse:true,nativeDragToDot:true,dragOutNoAccidentalOpen:true,restoreGeometry:true,twentyNotes:true,deliveryOrder:true},null,2));
 cursor(oldCursor.x,oldCursor.y);cursorRestored=true;await invoke(main,'exit_app',{discard:false}).catch(()=>{});console.log('PASS notebook idle, auxiliary pause, native drag/dot/restore and twenty-note order');
}finally{try{if(!cursorRestored&&!main.isClosed())cursor(oldCursor.x,oldCursor.y);}catch{}await b.close().catch(()=>{});}
})().catch(e=>{console.error(e);process.exit(1)});
