const { chromium }=require('C:/Users/ZHP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');fs.mkdirSync('.tools',{recursive:true});
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1040,height:780}});await page.emulateMedia({reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const shot=await browser.newPage({viewport:{width:540,height:210},deviceScaleFactor:1});await shot.setContent('<body style="margin:0;padding:20px;background:#f4f5f6;font:14px Segoe UI;color:#292b30"><table style="width:100%;border-collapse:collapse;text-align:left;line-height:2.6"><tr style="color:#717680"><th>商品</th><th>仓库</th><th>库存</th><th>更新时间</th></tr><tr><td>面料样品 A</td><td>A</td><td>12</td><td>09-11 10:24</td></tr><tr><td>面料样品 B</td><td>A</td><td>28</td><td>09-11 09:41</td></tr><tr><td>面料样品 C</td><td>B</td><td>6</td><td>09-11 09:12</td></tr></table></body>');const png=await shot.screenshot({path:'.tools/redesign-fixture.png'});await shot.close();const image='data:image/png;base64,'+png.toString('base64');
 const now=new Date(), yesterday=new Date(now);yesterday.setDate(now.getDate()-1);
 const make=(id,text,date,type='Note',attachments=[])=>({id,projectId:'p',type,text,createdAt:date.toISOString(),updatedAt:date.toISOString(),status:'Open',tags:id==='one'?['库存']:[],attachments,references:[]});
 const attachment={id:'image',name:'warehouse.png',path:image};
 const fixture={projects:[{id:'p',name:'订单系统'},{id:'q',name:'空项目'}],entries:[make('one','切换仓库后，库存没有刷新\n切换到 B 仓库后，列表仍显示之前的数据。',now,'Bug',[attachment]),make('two','保留筛选后的滚动位置\n返回列表时，希望能接着上次的位置继续查看。',new Date(now.getTime()-3600000),'UX'),make('three','整理好，再交给 Agent\n把相关记录放在一起，复制完整上下文。',yesterday),make('long','长文本验收\n'+('这是一段用于验证自动换行与阅读布局的长文本。'.repeat(35))+'\n'+('LongUnbrokenText'.repeat(35)),new Date(yesterday.getTime()-1000),'Feature',[attachment,{...attachment,id:'i2'},{...attachment,id:'i3'},{...attachment,id:'i4'}])],dataDir:'UI test only'};
 await page.addInitScript(({fixture})=>{let db=structuredClone(fixture);window.__TAURI_INTERNALS__={convertFileSrc:p=>p,invoke:async(cmd,args)=>{if(cmd==='load')return structuredClone(db);if(cmd==='create_project'){const p={id:crypto.randomUUID(),name:args.name};db.projects.push(p);return p;}if(cmd==='save_entry'){db.entries=db.entries.filter(e=>e.id!==args.entry.id);db.entries.push(JSON.parse(JSON.stringify(args.entry)));}if(cmd==='batch'){if(args.status==='Delete')db.entries=db.entries.filter(e=>!args.ids.includes(e.id));else db.entries.forEach(e=>{if(args.ids.includes(e.id))e.status=args.status;});}if(cmd==='copy_text')window.copied=args.text;if(cmd==='copy_images')return args.files.length;if(cmd==='export_bundle')return 'test-export';if(cmd==='add_image')return {id:crypto.randomUUID(),name:args.name,path:'data:image/png;base64,'+args.data};}};localStorage.setItem('devpad-theme','light');},{fixture});
 await page.goto('http://127.0.0.1:5173');await page.locator('article').first().waitFor();assert.equal(await page.locator('.composer').count(),0);assert.equal(await page.locator('.selection-check').count(),0);await page.screenshot({path:'.tools/redesign-light.png'});await page.locator('article .image-button').first().click();await page.getByRole('dialog',{name:'图片预览'}).waitFor();await page.keyboard.press('Escape');
 const theme=async(name)=>{await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('button',{name,exact:true}).click();await page.getByRole('button',{name:'关闭面板',exact:true}).click();};
 await theme('深色');await page.screenshot({path:'.tools/redesign-dark.png'});assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.keyboard.press('Control+f');await page.getByLabel('搜索记录').fill('库存');assert.equal(await page.locator('article').count(),1);await page.getByRole('button',{name:'清除全部',exact:true}).click();await page.getByLabel('收起搜索').click();
 await page.getByLabel('项目与筛选',{exact:true}).click();await page.getByRole('button',{name:'体验',exact:true}).click();await page.getByRole('button',{name:/查看 1 条笔记/}).click();assert.equal(await page.locator('article').count(),1);await page.getByRole('button',{name:'清除全部',exact:true}).click();
 await page.keyboard.press('Control+n');await page.getByLabel('记录内容').fill('新增验收笔记\n保持原文，不替换业务记录。 #mobile');await page.keyboard.press('Alt+3');assert.equal(await page.getByLabel('笔记类型').inputValue(),'Feature');await page.keyboard.press('Control+Enter');await page.waitForFunction(()=>document.querySelectorAll('article').length===5);assert.equal(await page.getByLabel('记录内容').evaluate(e=>e===document.activeElement),true);
 await page.getByLabel('笔记类型').selectOption('Draft');await page.getByLabel('记录内容').fill('本轮整理草稿');await page.getByLabel('引用已有笔记').selectOption('two');await page.getByLabel('引用已有笔记').selectOption('one');await page.getByLabel('上移引用').nth(1).click();await page.locator('input[type=file]').setInputFiles('.tools/redesign-fixture.png');await page.locator('.attachment').waitFor();await page.screenshot({path:'.tools/redesign-editor-dark.png'});await page.getByRole('button',{name:/^保存/}).click();await page.waitForFunction(()=>document.querySelectorAll('article').length===6);await page.getByLabel('收起编辑器').click();
 await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('button',{name:'选择笔记',exact:true}).click();await page.locator('.selection-check').nth(0).click();await page.locator('.selection-check').nth(2).click({modifiers:['Shift']});assert.equal(await page.locator('.selection-check[aria-pressed=true]').count(),3);await page.getByRole('button',{name:'交给 Agent',exact:true}).click();await page.getByRole('button',{name:'复制提示词',exact:true}).click();assert.match(await page.evaluate(()=>window.copied),/库存/);await page.screenshot({path:'.tools/redesign-delivery-dark.png'});await page.getByRole('button',{name:'关闭面板',exact:true}).click();
 for(const color of ['浅色','深色']){await theme(color);await page.setViewportSize({width:520,height:480});await page.locator('.notes-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await page.screenshot({path:'.tools/redesign-small-'+(color==='浅色'?'light':'dark')+'.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow');assert.ok(await page.locator('.notes-scroll').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'No inner horizontal overflow');const b=await page.locator('.bottom-area').boundingBox(),last=await page.locator('article').last().boundingBox();assert.ok(last.y+last.height<=b.y+1,'Toolbar must not cover last note');await page.keyboard.press('Control+n');await page.getByLabel('记录内容').fill('小窗口未保存的编辑');await page.screenshot({path:'.tools/redesign-small-editor-'+(color==='浅色'?'light':'dark')+'.png'});const save=await page.getByRole('button',{name:/^保存/}).boundingBox();assert.ok(save.y+save.height<=480,'Save stays inside window');await page.getByLabel('收起编辑器').click();}
 if(await page.getByRole('button',{name:'完成选择'}).count())await page.getByRole('button',{name:'完成选择'}).click();await page.getByRole('button',{name:'取消编辑',exact:true}).count().then(async n=>{if(n)await page.getByRole('button',{name:'取消编辑',exact:true}).click();});await page.locator('.note-menu').first().click();await page.getByRole('button',{name:'编辑',exact:true}).click();await page.getByRole('button',{name:'放弃编辑',exact:true}).click();await page.screenshot({path:'.tools/redesign-editing-dark.png'});await page.getByLabel('收起编辑器').click();await page.locator('.capture-bar').click();assert.equal(await page.getByLabel('笔记类型').inputValue(),'Draft');await page.getByRole('button',{name:'取消编辑',exact:true}).click();await page.getByRole('button',{name:'放弃编辑',exact:true}).click();await page.locator('.note-heading h2').nth(1).click({modifiers:['Control']});await page.locator('.note-heading h2').nth(2).click({modifiers:['Control']});assert.equal(await page.locator('.selection-check[aria-pressed=true]').count(),2);await page.getByRole('button',{name:'完成选择'}).click();await page.getByLabel('切换项目').click();await page.getByRole('button',{name:'空项目',exact:true}).click();await page.screenshot({path:'.tools/redesign-empty-dark.png'});assert.equal(await page.locator('article').count(),0);

 await page.getByLabel('切换项目').click();await page.getByRole('button',{name:'订单系统',exact:true}).click();
 const count=await page.locator('article').count();await page.locator('.note-menu').first().click();await page.getByRole('button',{name:'删除笔记',exact:true}).click();
 const confirmation=page.getByRole('dialog',{name:'删除这些记录？'});await confirmation.waitFor();assert.equal(await confirmation.getByRole('button',{name:'保留记录'}).evaluate(e=>document.activeElement===e),true);
 await page.screenshot({path:'.tools/confirmation-dark.png'});await page.keyboard.press('Escape');assert.equal(await page.locator('article').count(),count);
 await theme('浅色');await page.locator('.note-menu').first().click();await page.getByRole('button',{name:'删除笔记',exact:true}).click();await confirmation.waitFor();await page.screenshot({path:'.tools/confirmation-light.png'});await confirmation.getByRole('button',{name:'删除记录',exact:true}).click();await page.waitForFunction(count=>document.querySelectorAll('article').length===count-1,count);
 await page.keyboard.press('Control+n');await page.getByLabel('记录内容').fill('焦点验收');await page.getByLabel('笔记标签').click();assert.equal(await page.getByLabel('笔记标签').evaluate(e=>getComputedStyle(e).outlineStyle),'none');await page.getByLabel('记录内容').click();assert.equal(await page.getByLabel('记录内容').evaluate(e=>getComputedStyle(e).outlineStyle),'none');
 await page.getByRole('button',{name:'取消编辑',exact:true}).click();await page.getByRole('button',{name:'继续编辑',exact:true}).click();assert.equal(await page.getByLabel('记录内容').inputValue(),'焦点验收');
 assert.deepEqual(errors,[]);console.log('PASS themes, search/filter, shortcuts, save focus, Draft references/reorder, images, shift selection, delivery, 520x480 overflow/occlusion, empty state.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});



