const {chromium}=require('C:/Users/ZHP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const cp=require('node:child_process');
(async()=>{const browser=await chromium.connectOverCDP('http://127.0.0.1:9227');const page=browser.contexts()[0].pages()[0];await page.emulateMedia({reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'创建第一个项目'}).waitFor();
 const native=async(cmd)=>page.evaluate(cmd=>window.__TAURI_INTERNALS__.invoke('plugin:window|'+cmd,{label:'main'}),cmd);
 await page.getByLabel('窗口置顶',{exact:true}).click();assert.equal(await native('is_always_on_top'),true);await page.getByLabel('窗口置顶',{exact:true}).click();assert.equal(await native('is_always_on_top'),false);
 await page.getByLabel('最大化',{exact:true}).click();assert.equal(await native('is_maximized'),true);await page.getByLabel('还原窗口',{exact:true}).click();assert.equal(await native('is_maximized'),false);
 await page.getByRole('button',{name:'创建第一个项目'}).click();await page.getByLabel('项目名称',{exact:true}).fill('原生界面验收');await page.getByRole('button',{name:'创建项目',exact:true}).click();await page.getByLabel('记录内容').fill('切换仓库后，库存没有刷新\n保留原始文字与附件。 #库存');await page.locator('input[type=file]').setInputFiles('.tools/redesign-fixture.png');await page.locator('.attachment').waitFor();
 cp.execFileSync('powershell.exe',['-NoProfile','-STA','-Command','Add-Type -AssemblyName System.Windows.Forms; Add-Type -AssemblyName System.Drawing; $img=[System.Drawing.Image]::FromFile($env:DEVPAD_TEST_IMAGE); [System.Windows.Forms.Clipboard]::SetImage($img); $img.Dispose()'],{windowsHide:true,env:{...process.env,DEVPAD_TEST_IMAGE:require('node:path').resolve('.tools/redesign-fixture.png')}});
 await page.getByLabel('记录内容').focus();await page.keyboard.press('Control+v');await page.waitForFunction(()=>document.querySelectorAll('.attachment').length===2);await page.keyboard.press('Control+Enter');await page.locator('article').waitFor();assert.equal(await page.getByLabel('记录内容').evaluate(e=>document.activeElement===e),true);await page.getByLabel('收起编辑器').click();assert.equal(await page.locator('article img').first().evaluate(i=>i.naturalWidth),540);
 await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('button',{name:'浅色',exact:true}).click();await page.getByLabel('关闭面板',{exact:true}).click();await page.screenshot({path:'.tools/redesign-native-light.png'});
 await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('button',{name:'深色',exact:true}).click();await page.getByLabel('关闭面板',{exact:true}).click();await page.screenshot({path:'.tools/redesign-native-dark.png'});
 await page.locator('.note-menu').click();await page.getByRole('button',{name:'编辑笔记',exact:true}).click();await page.getByLabel('记录内容').fill('切换仓库后，库存没有刷新\n保留原始文字与附件。 #库存\n已补充复现步骤。');await page.keyboard.press('Control+Enter');await page.getByLabel('收起编辑器').click();
 await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('button',{name:'选择笔记',exact:true}).click();await page.getByRole('button',{name:'全选当前结果'}).click();await page.getByRole('button',{name:'Copy for Agent',exact:true}).click();await page.getByRole('button',{name:'复制提示词',exact:true}).click();const clip=cp.execFileSync('powershell.exe',['-NoProfile','-STA','-Command','Add-Type -AssemblyName System.Windows.Forms; [Console]::OutputEncoding=[System.Text.Encoding]::UTF8; [System.Windows.Forms.Clipboard]::GetText()'],{windowsHide:true,encoding:'utf8'});assert.ok(clip.includes('已补充复现步骤'));
 await page.getByRole('button',{name:/复制图片文件/}).click();const files=cp.execFileSync('powershell.exe',['-NoProfile','-STA','-Command','Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Clipboard]::GetFileDropList().Count'],{windowsHide:true,encoding:'utf8'});assert.equal(Number(files.trim()),2);await page.getByLabel('关闭面板',{exact:true}).click();await page.getByRole('button',{name:'完成',exact:true}).click();
 await page.reload();await page.locator('article').waitFor();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');const data=await page.evaluate(()=>window.__TAURI_INTERNALS__.invoke('load'));assert.equal(data.entries[0].status,'Done');assert.equal(data.entries[0].attachments.length,2);assert.match(data.entries[0].text,/已补充复现步骤/);fs.writeFileSync('.tools/redesign-native-result.json',JSON.stringify({passed:true,dataDir:data.dataDir,entries:data.entries.length,clipboardImages:2}));
 await page.keyboard.press('Control+n');await page.getByLabel('记录内容').fill('关闭保护验收');await page.getByLabel('关闭窗口',{exact:true}).click();await page.getByRole('dialog',{name:'关闭 DevPad？'}).waitFor();await page.getByRole('button',{name:'继续编辑',exact:true}).click();assert.equal(await page.getByLabel('记录内容').inputValue(),'关闭保护验收');await page.getByRole('button',{name:'取消编辑',exact:true}).click();
 await page.getByLabel('最小化',{exact:true}).click();assert.equal(await native('is_minimized'),true);const closed=page.waitForEvent('close',{timeout:10000});await page.evaluate(()=>document.querySelector('[aria-label=关闭窗口]').click());await closed;assert.deepEqual(errors,[]);console.log('PASS native theme persistence, pin/unpin, maximize/restore, minimize, close protection, image file+Windows paste, edit, text/CF_HDROP clipboard, batch status, SQLite reload, actual window exit.');await browser.close().catch(()=>{});
})().catch(e=>{console.error(e);process.exit(1)});

