import { test } from 'node:test';
import assert from 'node:assert/strict';
import { tagsOf, compose as exportCompose, exportTemplates, createDelivery, sourceChanged, deliveryFingerprint, editorSignature, type Entry } from './core.ts';
const compose=(project:string,entries:Entry[],all:Entry[]=entries,batch='PREVIEW')=>exportCompose(project,entries,all,batch,{...exportTemplates[3],metadata:true,numberImages:true});
const entry=(id:string,refs:string[]=[]):Entry=>({id,projectId:'p',type:'Bug',text:'问题 '+id,tags:[],attachments:[],status:'Open',createdAt:'2026-09-11',updatedAt:'2026-09-11',references:refs});
test('查看笔记和换行标准化不算修改，实际编辑与移动项目才算修改',()=>{const original={projectId:'a',type:'Note',text:'第一行\r\n第二行',tagInput:'#甲 #乙',attachments:[],references:['ref']};const before=editorSignature(original);assert.equal(before,editorSignature({...original,text:'第一行\n第二行',tagInput:'#乙 #甲'}));assert.notEqual(before,editorSignature({...original,text:'改动'}));assert.notEqual(before,editorSignature({...original,projectId:'b'}));assert.equal(before,editorSignature({...original}));});
test('交付快照隔离原记录，跨项目引用保留且修改只提示相关窗口',()=>{const a=entry('a',['b']),b={...entry('b'),projectId:'other'},c=entry('c');const session=createDelivery({id:'p',name:'A'},[a],[a,b,c],'12345678');assert.equal(session.records.length,2);c.text='无关修改';assert.equal(sourceChanged(session,[a,b,c]),false);b.text='引用修改';assert.equal(sourceChanged(session,[a,b,c]),true);assert.equal(session.records[1].text,'问题 b');assert.equal(sourceChanged(session,[b,c]),true);assert.equal(compose(session.project.name,[session.records[0]],session.records,session.batch).count,2);});
test('相同内容复制共用指纹，项目迁移改变指纹且提示内容变化',()=>{const a=entry('a');const session=createDelivery({id:'p',name:'A'},[a],[a],'12345678');a.updatedAt='later';assert.equal(sourceChanged(session,[a]),false);assert.equal(deliveryFingerprint(session),deliveryFingerprint(createDelivery({id:'p',name:'A'},[a],[a],'87654321')));a.projectId='other';assert.equal(sourceChanged(session,[a]),true);});
test('中文和连字符标签去重',()=>assert.deepEqual(tagsOf('#库存 #old-order #库存'),['库存','old-order']));
test('草稿按引用顺序展开、重复引用和循环安全',()=>{const a=entry('a',['c','b']),b=entry('b',['a']),c=entry('c');const out=compose('测试',[a,b],[a,b,c]).text;assert.ok(out.indexOf('问题 c')<out.indexOf('问题 b'));assert.equal(out.split('问题 a').length-1,1);});
test('同名图片生成不同文件名并与提示词对应',()=>{const a=entry('a');a.attachments=[{id:'first',name:'image.png',path:'C:/attachments/first.png'},{id:'second',name:'image.png',path:'C:/attachments/second.png'}];const out=compose('项目',[a]);assert.deepEqual(out.files.map(f=>f.name),['PREVIEW-R1-P1-001-image.png','PREVIEW-R1-P2-002-image.png']);out.files.forEach(f=>assert.ok(out.text.includes(f.name)));});
test('已删除引用忽略且保留当前记录',()=>assert.ok(compose('项目',[entry('a',['missing'])]).text.includes('问题 a')));

test('二十条记录与多图保持一一对应和输入顺序',()=>{const entries=Array.from({length:20},(_,i)=>({...entry(String(i)),attachments:[{id:String(i),name:'截图.png',path:'C:/attachments/'+i+'.png'}]}));const out=compose('项目',entries);assert.equal(out.count,20);assert.equal(new Set(out.files.map(f=>f.name)).size,20);out.files.forEach((f,i)=>{assert.equal(f.source,entries[i].attachments[0].path);assert.ok(out.text.indexOf(f.name)>out.text.indexOf('问题 '+i));});assert.ok(out.text.indexOf('问题 0')<out.text.indexOf('问题 19'));});

test('图内编号和批次与文本一致，引用也有独立编号，原记录不变',()=>{const a=entry('a',['b']),b=entry('b');a.attachments=[{id:'1',name:'original.jpg',path:'C:/attachments/1.jpg'}];b.attachments=[{id:'2',name:'original.webp',path:'C:/attachments/2.webp'}];const original=JSON.stringify([a,b]);const out=compose('项目',[a],[a,b],'A1B2C3D4');assert.deepEqual(out.files.map(f=>f.mark),[{record:1,picture:1,batch:'A1B2C3D4'},{record:2,picture:1,batch:'A1B2C3D4'}]);assert.ok(out.text.includes('记录 2 · 图片 1'));assert.ok(out.files.every(f=>f.name.endsWith('.png')));assert.equal(JSON.stringify([a,b]),original);});
